# This file is used to deploy your application to Render.
# It defines a single web service for your Flask application.

services:
  - type: web
    name: study-pal-bible-app
    env: python
    pythonVersion: 3.11.x # Using a stable Python version
    buildCommand: "pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg" # Install ffmpeg
    startCommand: "gunicorn main:app" # Ensure this points to your Flask app in main.py
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: GIT_PAT
        sync: false # This is sensitive and should be set in Render dashboard
