# This file is used to deploy your application to Render.
# It defines a single web service for your Flask application.

services:
  - type: web
    name: study-pal-bible-app
    env: python
    region: oregon # Specify a region, e.g., oregon
    plan: free # Explicitly set to free plan
    pythonVersion: 3.11.6 # Using a specific stable Python version
    buildCommand: "pip install -r requirements.txt && apt-get update -y && apt-get install -y ffmpeg"
    startCommand: "gunicorn main:app"
    disk:
      name: mydata
      mountPath: /var/data
      sizeGB: 1 # Allocate 1GB of persistent storage
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: GIT_PAT
        sync: false
    build:
      packages:
        - ffmpeg
